name: Sync Pipelineruns

run-name: Sync Pipelineruns

on:
  workflow_dispatch:

jobs:
  dummy-job:
    runs-on: ubuntu-latest
    steps:

      - name: Message
        run: |
          echo "This workflow should only run for release branches"
          echo "Please select the release branch from the dropdown at the time of triggering the workflow!"